# Generated by Django 5.0 on 2024-09-04 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default='Tutor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category'),
        ),
    ]
